#!/bin/bash


kjupyter() {
#  (sleep 3 && open "http://$(docker-machine ip docker2):8888")&
  docker run -v "$PWD":/tmp/working -w=/tmp/working -p 8888:8888 --rm -it kaggle/python jupyter notebook --no-browser --ip="0.0.0.0" --notebook-dir=/tmp/working --allow-root 
}

kjupyter

