#!/bin/bash

cat << 'EOS' > README.md 
# One line title


## What is this?


## Requirements

Currently supported following environment.

## Current features

- list up features

## How to use?



```Examples
$ xxxx 
```

## TODO
- list

## Authors

- [@makotow](https://github.com/makotow)

## License

MIT

EOS

