#!/bin/bash

cat << 'EOS' > README.md
# One line title

*Read this in other languages: [日本語](README.ja.md)

## What is this?


## Requirements

Currently supported following environment.

## Current features

- list up features

## How to use?



```Examples
$ xxxx
```

## TODO
- list

## Authors

- [@makotow](https://github.com/makotow)

## License

MIT

EOS


cat << 'EOS' > README.ja.md
# One line title

* 他の言語で読む: [English](README.md)

## これはなに?


## 前提条件

現在は以下の環境をサポートしています。

## 現在の機能

- list up features

## 使い方



```Examples
$ xxxx
```

## TODO
- list

## Authors

- [@makotow](https://github.com/makotow)

## ライセンス

MIT

EOS