#!/bin/sh
set -eu

usage() {
    cat <<EOF
$(basename "${0}") is a tool which is generating  presentation preparation.
Make directories(reference, images, outline idea) and copy template file.

The template file can be copied by selecting from the directory specified by the argument.

Usage:
   $(basename "${0}") path_to_template_file_dir
EOF
}

if [ $# -ne 1 ] ; then
    echo "Please set powerpoint template path."
    usage
    exit 1
fi

TEMPLATE_PATH="${1}"

# search template file with peco
filename=$(find "${TEMPLATE_PATH}" -maxdepth 1 -type f | peco)

# copy  template file to target
cp "${filename}" "$(pwd)"

mkdir idea outline images reference
touch .gitignore

echo "Setup done"
